import { createElement } from 'lwc';
import DataTable_3_RowSelection from 'c/dataTable_3_RowSelection';

describe('c-data-table-3-row-selection', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-data-table-3-row-selection', {
            is: DataTable_3_RowSelection
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});